language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

install: composer require --no-update guzzlehttp/guzzle $GUZZLE_VERSION; composer update

script: vendor/bin/phpunit

env:
  - GUZZLE_VERSION: 6.0
  - GUZZLE_VERSION: 6.2
  - GUZZLE_VERSION: 6.*
