language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - hhvm

install: composer require --no-update guzzlehttp/guzzle $GUZZLE_VERSION; composer update

script: vendor/bin/phpunit

env:
  - GUZZLE_VERSION: 6.0
  - GUZZLE_VERSION: 6.1
