language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm

install: composer require --no-update guzzlehttp/guzzle $GUZZLE_VERSION; composer update

script: vendor/bin/phpunit

env:
  - GUZZLE_VERSION: 4.2
  - GUZZLE_VERSION: 5.0
  - GUZZLE_VERSION: 5.2
